### ISSUE TITLE
No module named tsys01

### ISSUE THREAD

**Issue by tdritter** [bluerobotics/tsys01-python#4]
Hey guys,

Been trying to run these scripts on a RPi 3B+ and I keep getting an import error, "no module named tsys01." I've installed python-smbus, updated, upgraded, etc. At the moment I'm just trying to run the "example.py" script. Am I missing something super obvious here?

Thanks in advance!

**Comment by ChrisTorres342** [comment]
Hi. I am having the same problem. By any chance did you find out how to make it work? Thanks in advance! :)

**Comment by patrickelectric** [comment]
Hi, you need to download the library with:
`git clone https://github.com/bluerobotics/tsys01-python`
Go to tsys01-python folder and install the library with:
`sudo python setup.py install`
